[package]
name = "bitbar-speedruncom"
version = "0.2.1"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[[bin]]
name = "bitbar-speedruncom"
path = "src/main.rs"
doc = false
test = false
bench = false

[dependencies]
css-color-parser = "*"
itertools = "*"
notify-rust = "3"
serde = "1"
serde_derive = "1"
serde_json = "1"
wrapped_enum = "*"
xdg-basedir = "1"

[dependencies.bitbar]
git = "https://github.com/fenhl/rust-bitbar"

[dependencies.srcomapi]
git = "https://github.com/fenhl/srcomapi-rs"

[patch.crates-io]
native-tls = { git = "https://github.com/fenhl/rust-native-tls", branch = "fix-deps" } # until https://github.com/sfackler/rust-native-tls/issues/119 is fixed
