[package]
name = "bitbar-speedruncom"
version = "0.1.0"
authors = ["Fenhl <fenhl@fenhl.net>"]

[[bin]]
name = "bitbar-speedruncom"
path = "src/main.rs"
doc = false
test = false
bench = false

[dependencies]
wrapped_enum = "*"
