[package]
name = "bitbar-speedruncom"
version = "0.1.0"
authors = ["Fenhl <fenhl@fenhl.net>"]

[[bin]]
name = "bitbar-speedruncom"
path = "src/main.rs"
doc = false
test = false
bench = false

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
wrapped_enum = "*"
xdg-basedir = "1.0"

[dependencies.srcomapi]
git = "https://github.com/fenhl/srcomapi-rs"
